# Generated by Django 3.2.13 on 2022-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='root', max_length=32)),
                ('password', models.CharField(default='123456', max_length=32)),
                ('fileName', models.CharField(default='data', max_length=32)),
                ('CreateTime', models.DateField(blank=True, help_text='操作记录时间', null=True)),
                ('algorithm', models.CharField(default='fgsm', max_length=32)),
            ],
            options={
                'db_table': 'recordT',
            },
        ),
    ]
