# Generated by Django 3.2.13 on 2022-05-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserC',
        ),
    ]
