# Generated by Django 3.2.13 on 2022-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='root', max_length=32)),
                ('password', models.CharField(default='123456', max_length=32)),
            ],
            options={
                'db_table': 'userT',
            },
        ),
    ]
